FROM python:3.8

ENV instagram_username ""
ENV instagram_password ""
ENV SCREEN_SOURCE ""

COPY Scripts/requirements.txt /requirements.txt
COPY Scripts/post_insta.py /post_insta.py

RUN pip install -r requirements.txt
ENTRYPOINT python3 /post_insta.py
