FROM python:3.8

ENV twitter_consumer_key ""
ENV twitter_consumer_secret ""
ENV twitter_access_token ""
ENV twitter_access_token_secret ""

COPY Scripts/requirements.txt /requirements.txt
COPY Scripts/post.py /post.py

RUN pip install -r requirements.txt
ENTRYPOINT python3 /post.py
